Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind5]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3172' is not allowed to depart on edge '510869557#1'.
Warning: The vehicle '3172' has no valid route.
Warning: Vehicle '282' is not allowed to depart on edge '5687424
[ind5] routes.xml: exists=True  size=705436
[ind5] meandata.add.xml written
[ind5] >>> sumo
[ind5]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpfy54symb\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpfy54symb\meandata.add.xml" --no-step-log true --no-warnings true
[ind5]     rc=0  elapsed=19.01s
[ind5] edges.xml: exists=True  size=126843
[ind5] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:30:40.732478+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind5] sim edges=358  common=357  score=0.044508
[ind5] ── DONE  total=21.40s ──────────
  → ind5 score=0.044508  (3/6 done)
[ind3] ── START  pid=19964 ──────────
[ind3] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpfor3l6st
[ind3] od.xml written  size=6068
[ind3] >>> od2trips
[ind3]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpfor3l6st\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpfor3l6st\trips.xml"
[ind3]     rc=0  elapsed=0.45s
[ind3]     stdout: Parsing time 0.00
Parsing time 1.84
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.70
Parsing time 10.87
Parsing time 12.17
Parsing time 14.07
Parsing time 15.74
Parsing time 18.30
Parsing time 19.61
Parsing time 21.76
Parsing time 22.82
Parsing time 23.87
Parsing time 25.12
Pa
[ind3] trips.xml: exists=True  size=935440
[ind3] >>> duarouter
[ind3]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpfor3l6st\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpfor3l6st\routes.rou.xml" --ignore-errors true
[ind3]     rc=0  elapsed=2.09s
[ind3]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind3]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3173' is not allowed to depart on edge '510869557#1'.
Warning: The vehicle '3173' has no valid route.
Warning: Vehicle '282' is not allowed to depart on edge '5687424
[ind3] routes.xml: exists=True  size=740168
[ind3] meandata.add.xml written
[ind3] >>> sumo
[ind3]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpfor3l6st\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpfor3l6st\meandata.add.xml" --no-step-log true --no-warnings true
[ind3]     rc=0  elapsed=19.28s
[ind3] edges.xml: exists=True  size=126872
[ind3] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:30:40.904126+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind3] sim edges=359  common=359  score=0.036477
[ind3] ── DONE  total=21.84s ──────────
  → ind3 score=0.036477  (4/6 done)
[ind0] ── START  pid=15352 ──────────
[ind0] tmpdir: C:\Users\milad\AppData\Local\Temp\tmp7amlm_a9
[ind0] od.xml written  size=6066
[ind0] >>> od2trips
[ind0]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmp7amlm_a9\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmp7amlm_a9\trips.xml"
[ind0]     rc=0  elapsed=0.37s
[ind0]     stdout: Parsing time 0.00
Parsing time 1.88
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.70
Parsing time 10.87
Parsing time 12.17
Parsing time 14.07
Parsing time 15.55
Parsing time 16.72
Parsing time 18.06
Parsing time 19.61
Parsing time 21.21
Parsing time 22.28
Parsing time 23.87
Pa
[ind0] trips.xml: exists=True  size=946026
[ind0] >>> duarouter
[ind0]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmp7amlm_a9\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmp7amlm_a9\routes.rou.xml" --ignore-errors true
[ind0]     rc=0  elapsed=2.16s
[ind0]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind0]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3170' is not allowed to depart on edge '510869557#1'.
Warning: The vehicle '3170' has no valid route.
Warning: Vehicle '282' is not allowed to depart on edge '5687424
[ind0] routes.xml: exists=True  size=703499
[ind0] meandata.add.xml written
[ind0] >>> sumo
[ind0]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmp7amlm_a9\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmp7amlm_a9\meandata.add.xml" --no-step-log true --no-warnings true
[ind0]     rc=0  elapsed=22.09s
[ind0] edges.xml: exists=True  size=127392
[ind0] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:30:40.933401+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind0] sim edges=359  common=358  score=0.031673
[ind0] ── DONE  total=24.63s ──────────
  → ind0 score=0.031673  (5/6 done)
[ind2] ── START  pid=7116 ──────────
[ind2] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpepgrr6wk
[ind2] od.xml written  size=6065
[ind2] >>> od2trips
[ind2]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpepgrr6wk\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpepgrr6wk\trips.xml"
[ind2]     rc=0  elapsed=0.36s
[ind2]     stdout: Parsing time 0.00
Parsing time 1.88
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.70
Parsing time 11.00
Parsing time 12.17
Parsing time 14.07
Parsing time 15.75
Parsing time 18.30
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Parsing time 25.12
Pa
[ind2] trips.xml: exists=True  size=905638
[ind2] >>> duarouter
[ind2]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpepgrr6wk\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpepgrr6wk\routes.rou.xml" --ignore-errors true
[ind2]     rc=0  elapsed=2.11s
[ind2]     stdout: Reading up to time step: 0.77
Reading up to time step: 200.77
Reading up to time step: 400.77
Reading up to time step: 600.77
Reading up to time step: 800.77
Reading up to time step: 1000.77
Reading up to time step: 1200.77
Reading up to time step: 1400.77
Reading up to time step: 1600.77
Reading up
[ind2]     stderr: Warning: No connection between edge '4336627#1' and edge '489274164#0' found.
Warning: Mandatory edge '489274164#0' not reachable by vehicle '3826'.
Warning: The vehicle '3826' has no valid route.
Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no 
[ind2] routes.xml: exists=True  size=686855
[ind2] meandata.add.xml written
[ind2] >>> sumo
[ind2]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpepgrr6wk\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpepgrr6wk\meandata.add.xml" --no-step-log true --no-warnings true
[ind2]     rc=0  elapsed=22.19s
[ind2] edges.xml: exists=True  size=127503
[ind2] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:30:40.904117+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind2] sim edges=359  common=358  score=0.031911
[ind2] ── DONE  total=24.68s ──────────
  → ind2 score=0.031911  (6/6 done)
  Gen 27 done in 25.1s  scores=['0.0317', '0.0348', '0.0319', '0.0365', '0.0391', '0.0445']
  All-time best: 0.024652

=== Generation 28 ===  pop=6  workers=6
  6 futures submitted, waiting...
[ind3] ── START  pid=14304 ──────────
[ind3] tmpdir: C:\Users\milad\AppData\Local\Temp\tmp4vx_elrt
[ind3] od.xml written  size=6065
[ind3] >>> od2trips
[ind3]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmp4vx_elrt\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmp4vx_elrt\trips.xml"
[ind3]     rc=0  elapsed=0.41s
[ind3]     stdout: Parsing time 0.00
Parsing time 1.84
Parsing time 4.33
Parsing time 6.04
Parsing time 7.63
Parsing time 8.70
Parsing time 10.87
Parsing time 12.17
Parsing time 14.07
Parsing time 15.75
Parsing time 18.30
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Parsing time 25.12
Pa
[ind3] trips.xml: exists=True  size=878418
[ind3] >>> duarouter
[ind3]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmp4vx_elrt\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmp4vx_elrt\routes.rou.xml" --ignore-errors true
[ind3]     rc=0  elapsed=2.34s
[ind3]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind3]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: No connection between edge '4337771#1' and edge '425989942#0' found.
Warning: Mandatory edge '425989942#0' not reachable by vehicle '3168'.
Warning: The vehicle '3168' has no 
[ind3] routes.xml: exists=True  size=699715
[ind3] meandata.add.xml written
[ind3] >>> sumo
[ind3]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmp4vx_elrt\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmp4vx_elrt\meandata.add.xml" --no-step-log true --no-warnings true
[ind3]     rc=0  elapsed=22.59s
[ind3] edges.xml: exists=True  size=127348
[ind3] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:06.449973+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind3] sim edges=360  common=359  score=0.030547
[ind3] ── DONE  total=25.37s ──────────
  → ind3 score=0.030547  (1/6 done)
[ind1] ── START  pid=7240 ──────────
[ind1] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpzdy10ss8
[ind1] od.xml written  size=6068
[ind1] >>> od2trips
[ind1]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpzdy10ss8\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpzdy10ss8\trips.xml"
[ind1]     rc=0  elapsed=0.43s
[ind1]     stdout: Parsing time 0.00
Parsing time 1.88
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.97
Parsing time 10.87
Parsing time 12.17
Parsing time 15.14
Parsing time 16.72
Parsing time 18.30
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Parsing time 25.12
Pa
[ind1] trips.xml: exists=True  size=923329
[ind1] >>> duarouter
[ind1]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpzdy10ss8\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpzdy10ss8\routes.rou.xml" --ignore-errors true
[ind1]     rc=0  elapsed=2.47s
[ind1]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind1]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3171' is not allowed to depart on edge '510869557#1'.
Warning: The vehicle '3171' has no valid route.
Warning: Vehicle '282' is not allowed to depart on edge '5687424
[ind1] routes.xml: exists=True  size=694318
[ind1] meandata.add.xml written
[ind1] >>> sumo
[ind1]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpzdy10ss8\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpzdy10ss8\meandata.add.xml" --no-step-log true --no-warnings true
[ind1]     rc=0  elapsed=24.01s
[ind1] edges.xml: exists=True  size=127194
[ind1] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:06.587742+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind1] sim edges=359  common=359  score=0.050095
[ind1] ── DONE  total=26.92s ──────────
  → ind1 score=0.050095  (2/6 done)
[ind2] ── START  pid=3780 ──────────
[ind2] tmpdir: C:\Users\milad\AppData\Local\Temp\tmppjkxbfwf
[ind2] od.xml written  size=6020
[ind2] >>> od2trips
[ind2]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmppjkxbfwf\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmppjkxbfwf\trips.xml"
[ind2]     rc=0  elapsed=0.40s
[ind2]     stdout: Parsing time 0.00
Parsing time 1.88
Parsing time 4.33
Parsing time 6.04
Parsing time 7.63
Parsing time 8.70
Parsing time 10.87
Parsing time 12.17
Parsing time 14.89
Parsing time 15.90
Parsing time 18.06
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Parsing time 25.71
Pa
[ind2] trips.xml: exists=True  size=912880
[ind2] >>> duarouter
[ind2]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmppjkxbfwf\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmppjkxbfwf\routes.rou.xml" --ignore-errors true
[ind2]     rc=0  elapsed=2.49s
[ind2]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind2]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3172' is not allowed to depart on edge '510869557#1'.
Warning: The vehicle '3172' has no valid route.
Warning: Vehicle '282' is not allowed to depart on edge '5687424
[ind2] routes.xml: exists=True  size=685465
[ind2] meandata.add.xml written
[ind2] >>> sumo
[ind2]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmppjkxbfwf\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmppjkxbfwf\meandata.add.xml" --no-step-log true --no-warnings true
[ind2]     rc=0  elapsed=24.55s
[ind2] edges.xml: exists=True  size=127660
[ind2] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:06.540150+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind2] sim edges=361  common=360  score=0.034989
[ind2] ── DONE  total=27.45s ──────────
  → ind2 score=0.034989  (3/6 done)
[ind0] ── START  pid=20044 ──────────
[ind0] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpt3hmgfks
[ind0] od.xml written  size=6110
[ind0] >>> od2trips
[ind0]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpt3hmgfks\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpt3hmgfks\trips.xml"
[ind0]     rc=0  elapsed=0.40s
[ind0]     stdout: Parsing time 0.00
Parsing time 1.88
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.70
Parsing time 10.87
Parsing time 12.17
Parsing time 15.75
Parsing time 18.06
Parsing time 19.61
Parsing time 21.76
Parsing time 22.82
Parsing time 23.87
Parsing time 25.12
Parsing time 26.95
Pa
[ind0] trips.xml: exists=True  size=925869
[ind0] >>> duarouter
[ind0]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpt3hmgfks\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpt3hmgfks\routes.rou.xml" --ignore-errors true
[ind0]     rc=0  elapsed=2.45s
[ind0]     stdout: Reading up to time step: 0.77
Reading up to time step: 200.77
Reading up to time step: 400.77
Reading up to time step: 600.77
Reading up to time step: 800.77
Reading up to time step: 1000.77
Reading up to time step: 1200.77
Reading up to time step: 1400.77
Reading up to time step: 1600.77
Reading up
[ind0]     stderr: Warning: Vehicle '3826' is not allowed to arrive on edge '489274200#1'.
Warning: The vehicle '3826' has no valid route.
Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3170' is not allowed to depart on edge '510869
[ind0] routes.xml: exists=True  size=708033
[ind0] meandata.add.xml written
[ind0] >>> sumo
[ind0]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpt3hmgfks\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpt3hmgfks\meandata.add.xml" --no-step-log true --no-warnings true
[ind0]     rc=0  elapsed=25.05s
[ind0] edges.xml: exists=True  size=127519
[ind0] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:06.575979+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind0] sim edges=359  common=359  score=0.032652
[ind0] ── DONE  total=27.92s ──────────
  → ind0 score=0.032652  (4/6 done)
[ind4] ── START  pid=2788 ──────────
[ind4] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpbdh7x6nc
[ind4] od.xml written  size=6112
[ind4] >>> od2trips
[ind4]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpbdh7x6nc\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpbdh7x6nc\trips.xml"
[ind4]     rc=0  elapsed=0.37s
[ind4]     stdout: Parsing time 0.00
Parsing time 1.88
Parsing time 4.33
Parsing time 6.04
Parsing time 7.63
Parsing time 8.97
Parsing time 10.87
Parsing time 12.17
Parsing time 14.07
Parsing time 15.75
Parsing time 18.30
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Parsing time 25.12
Pa
[ind4] trips.xml: exists=True  size=888397
[ind4] >>> duarouter
[ind4]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpbdh7x6nc\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpbdh7x6nc\routes.rou.xml" --ignore-errors true
[ind4]     rc=0  elapsed=2.38s
[ind4]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind4]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '282' is not allowed to depart on edge '568742440#1'.
Warning: The vehicle '282' has no valid route.
Warning: No connection between edge '313324686#1' and edge '445321
[ind4] routes.xml: exists=True  size=690132
[ind4] meandata.add.xml written
[ind4] >>> sumo
[ind4]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpbdh7x6nc\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpbdh7x6nc\meandata.add.xml" --no-step-log true --no-warnings true
[ind4]     rc=0  elapsed=27.40s
[ind4] edges.xml: exists=True  size=127717
[ind4] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:06.459161+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind4] sim edges=359  common=358  score=0.039188
[ind4] ── DONE  total=30.17s ──────────
  → ind4 score=0.039188  (5/6 done)
[ind5] ── START  pid=7476 ──────────
[ind5] tmpdir: C:\Users\milad\AppData\Local\Temp\tmp5sayymsv
[ind5] od.xml written  size=6019
[ind5] >>> od2trips
[ind5]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmp5sayymsv\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmp5sayymsv\trips.xml"
[ind5]     rc=0  elapsed=0.40s
[ind5]     stdout: Parsing time 0.00
Parsing time 1.84
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.70
Parsing time 10.87
Parsing time 12.84
Parsing time 14.07
Parsing time 15.75
Parsing time 18.30
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Parsing time 25.12
Pa
[ind5] trips.xml: exists=True  size=881509
[ind5] >>> duarouter
[ind5]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmp5sayymsv\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmp5sayymsv\routes.rou.xml" --ignore-errors true
[ind5]     rc=0  elapsed=2.40s
[ind5]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind5]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: No connection between edge '57388586' and edge '425989942#3' found.
Warning: Mandatory edge '425989942#3' not reachable by vehicle '1158'.
Warning: The vehicle '1158' has no v
[ind5] routes.xml: exists=True  size=689638
[ind5] meandata.add.xml written
[ind5] >>> sumo
[ind5]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmp5sayymsv\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmp5sayymsv\meandata.add.xml" --no-step-log true --no-warnings true
[ind5]     rc=0  elapsed=27.94s
[ind5] edges.xml: exists=True  size=127084
[ind5] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:06.555059+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind5] sim edges=357  common=357  score=0.039202
[ind5] ── DONE  total=30.76s ──────────
  → ind5 score=0.039202  (6/6 done)
  Gen 28 done in 31.2s  scores=['0.0327', '0.0501', '0.0350', '0.0305', '0.0392', '0.0392']
  All-time best: 0.024652

=== Generation 29 ===  pop=6  workers=6
  6 futures submitted, waiting...
[ind3] ── START  pid=4808 ──────────
[ind3] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpg5t3wm09
[ind3] od.xml written  size=6066
[ind3] >>> od2trips
[ind3]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpg5t3wm09\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpg5t3wm09\trips.xml"
[ind3]     rc=0  elapsed=0.34s
[ind3]     stdout: Parsing time 0.00
Parsing time 1.84
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.70
Parsing time 10.87
Parsing time 12.17
Parsing time 14.07
Parsing time 15.75
Parsing time 18.06
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Parsing time 25.12
Pa
[ind3] trips.xml: exists=True  size=890898
[ind3] >>> duarouter
[ind3]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpg5t3wm09\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpg5t3wm09\routes.rou.xml" --ignore-errors true
[ind3]     rc=0  elapsed=2.55s
[ind3]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind3]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '1160' is not allowed to arrive on edge '568742440#0'.
Warning: The vehicle '1160' has no valid route.
Warning: No connection between edge '4337771#1' and edge '451559
[ind3] routes.xml: exists=True  size=691552
[ind3] meandata.add.xml written
[ind3] >>> sumo
[ind3]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpg5t3wm09\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpg5t3wm09\meandata.add.xml" --no-step-log true --no-warnings true
[ind3]     rc=0  elapsed=16.28s
[ind3] edges.xml: exists=True  size=125863
[ind3] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:37.722266+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind3] sim edges=358  common=358  score=0.067355
[ind3] ── DONE  total=19.20s ──────────
  → ind3 score=0.067355  (1/6 done)
[ind0] ── START  pid=18444 ──────────
[ind0] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpqicmux8s
[ind0] od.xml written  size=6020
[ind0] >>> od2trips
[ind0]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpqicmux8s\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpqicmux8s\trips.xml"
[ind0]     rc=0  elapsed=0.39s
[ind0]     stdout: Parsing time 0.00
Parsing time 1.84
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.70
Parsing time 10.87
Parsing time 12.17
Parsing time 14.43
Parsing time 15.75
Parsing time 18.39
Parsing time 19.61
Parsing time 21.21
Parsing time 22.69
Parsing time 23.89
Parsing time 25.71
Pa
[ind0] trips.xml: exists=True  size=876347
[ind0] >>> duarouter
[ind0]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpqicmux8s\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpqicmux8s\routes.rou.xml" --ignore-errors true
[ind0]     rc=0  elapsed=2.60s
[ind0]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind0]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3166' is not allowed to depart on edge '510869557#1'.
Warning: The vehicle '3166' has no valid route.
Warning: Vehicle '281' is not allowed to depart on edge '5687424
[ind0] routes.xml: exists=True  size=663112
[ind0] meandata.add.xml written
[ind0] >>> sumo
[ind0]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpqicmux8s\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpqicmux8s\meandata.add.xml" --no-step-log true --no-warnings true
[ind0]     rc=0  elapsed=18.31s
[ind0] edges.xml: exists=True  size=126996
[ind0] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:37.773024+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind0] sim edges=361  common=360  score=0.055767
[ind0] ── DONE  total=21.32s ──────────
  → ind0 score=0.055767  (2/6 done)
[ind5] ── START  pid=9564 ──────────
[ind5] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpv5bklkbp
[ind5] od.xml written  size=6021
[ind5] >>> od2trips
[ind5]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpv5bklkbp\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpv5bklkbp\trips.xml"
[ind5]     rc=0  elapsed=0.38s
[ind5]     stdout: Parsing time 0.00
Parsing time 1.88
Parsing time 3.21
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.97
Parsing time 10.87
Parsing time 12.17
Parsing time 14.07
Parsing time 15.75
Parsing time 18.06
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Par
[ind5] trips.xml: exists=True  size=907398
[ind5] >>> duarouter
[ind5]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpv5bklkbp\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpv5bklkbp\routes.rou.xml" --ignore-errors true
[ind5]     rc=0  elapsed=2.51s
[ind5]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind5]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3170' is not allowed to depart on edge '510869557#1'.
Warning: The vehicle '3170' has no valid route.
Warning: Vehicle '282' is not allowed to depart on edge '5687424
[ind5] routes.xml: exists=True  size=714949
[ind5] meandata.add.xml written
[ind5] >>> sumo
[ind5]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpv5bklkbp\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpv5bklkbp\meandata.add.xml" --no-step-log true --no-warnings true
[ind5]     rc=0  elapsed=20.86s
[ind5] edges.xml: exists=True  size=127601
[ind5] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:37.691723+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind5] sim edges=361  common=360  score=0.027329
[ind5] ── DONE  total=23.76s ──────────
  → ind5 score=0.027329  (3/6 done)
[ind4] ── START  pid=11880 ──────────
[ind4] tmpdir: C:\Users\milad\AppData\Local\Temp\tmp3ifxiab_
[ind4] od.xml written  size=6068
[ind4] >>> od2trips
[ind4]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmp3ifxiab_\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmp3ifxiab_\trips.xml"
[ind4]     rc=0  elapsed=0.39s
[ind4]     stdout: Parsing time 0.00
Parsing time 1.88
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.70
Parsing time 10.87
Parsing time 12.17
Parsing time 14.07
Parsing time 15.55
Parsing time 16.72
Parsing time 18.39
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Pa
[ind4] trips.xml: exists=True  size=942909
[ind4] >>> duarouter
[ind4]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmp3ifxiab_\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmp3ifxiab_\routes.rou.xml" --ignore-errors true
[ind4]     rc=0  elapsed=2.66s
[ind4]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind4]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3171' is not allowed to depart on edge '510869557#1'.
Warning: The vehicle '3171' has no valid route.
Warning: Vehicle '282' is not allowed to depart on edge '5687424
[ind4] routes.xml: exists=True  size=740476
[ind4] meandata.add.xml written
[ind4] >>> sumo
[ind4]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmp3ifxiab_\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmp3ifxiab_\meandata.add.xml" --no-step-log true --no-warnings true
[ind4]     rc=0  elapsed=21.43s
[ind4] edges.xml: exists=True  size=127164
[ind4] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:37.855169+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind4] sim edges=359  common=358  score=0.032806
[ind4] ── DONE  total=24.51s ──────────
  → ind4 score=0.032806  (4/6 done)
[ind1] ── START  pid=20888 ──────────
[ind1] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpvf6afcp4
[ind1] od.xml written  size=6020
[ind1] >>> od2trips
[ind1]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpvf6afcp4\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpvf6afcp4\trips.xml"
[ind1]     rc=0  elapsed=0.37s
[ind1]     stdout: Parsing time 0.00
Parsing time 1.84
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.55
Parsing time 10.16
Parsing time 11.33
Parsing time 14.07
Parsing time 15.90
Parsing time 18.30
Parsing time 19.61
Parsing time 21.21
Parsing time 22.42
Parsing time 23.87
Parsing time 25.12
Pa
[ind1] trips.xml: exists=True  size=875109
[ind1] >>> duarouter
[ind1]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpvf6afcp4\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpvf6afcp4\routes.rou.xml" --ignore-errors true
[ind1]     rc=0  elapsed=2.48s
[ind1]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind1]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '1160' is not allowed to depart on edge '675273166'.
Warning: The vehicle '1160' has no valid route.
Warning: Vehicle '3173' is not allowed to depart on edge '51086955
[ind1] routes.xml: exists=True  size=687283
[ind1] meandata.add.xml written
[ind1] >>> sumo
[ind1]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpvf6afcp4\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpvf6afcp4\meandata.add.xml" --no-step-log true --no-warnings true
[ind1]     rc=0  elapsed=23.85s
[ind1] edges.xml: exists=True  size=127377
[ind1] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:37.656240+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind1] sim edges=359  common=359  score=0.029213
[ind1] ── DONE  total=26.71s ──────────
  → ind1 score=0.029213  (5/6 done)
[ind2] ── START  pid=15688 ──────────
[ind2] tmpdir: C:\Users\milad\AppData\Local\Temp\tmpnf7oa9ho
[ind2] od.xml written  size=6067
[ind2] >>> od2trips
[ind2]     cmd: od2trips -z "C:\Users\milad\AppData\Local\Temp\tmpnf7oa9ho\od.xml" -n "C:\R_and_D\digital-twin\sumo\od-prediction\grids.taz.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpnf7oa9ho\trips.xml"
[ind2]     rc=0  elapsed=0.38s
[ind2]     stdout: Parsing time 0.00
Parsing time 1.88
Parsing time 4.33
Parsing time 6.04
Parsing time 7.36
Parsing time 8.70
Parsing time 10.87
Parsing time 14.07
Parsing time 15.14
Parsing time 16.72
Parsing time 18.30
Parsing time 19.61
Parsing time 21.76
Parsing time 22.82
Parsing time 23.87
Parsing time 25.12
Pa
[ind2] trips.xml: exists=True  size=913484
[ind2] >>> duarouter
[ind2]     cmd: duarouter -n "C:\R_and_D\digital-twin\sumo\od-prediction\map.net.xml" -r "C:\Users\milad\AppData\Local\Temp\tmpnf7oa9ho\trips.xml" -o "C:\Users\milad\AppData\Local\Temp\tmpnf7oa9ho\routes.rou.xml" --ignore-errors true
[ind2]     rc=0  elapsed=2.56s
[ind2]     stdout: Reading up to time step: 0.79
Reading up to time step: 200.79
Reading up to time step: 400.79
Reading up to time step: 600.79
Reading up to time step: 800.79
Reading up to time step: 1000.79
Reading up to time step: 1200.79
Reading up to time step: 1400.79
Reading up to time step: 1600.79
Reading up
[ind2]     stderr: Warning: Vehicle '63' is not allowed to depart on edge '568742440#0'.
Warning: The vehicle '63' has no valid route.
Warning: Vehicle '3170' is not allowed to depart on edge '510869557#1'.
Warning: The vehicle '3170' has no valid route.
Warning: Vehicle '282' is not allowed to depart on edge '5687424
[ind2] routes.xml: exists=True  size=701325
[ind2] meandata.add.xml written
[ind2] >>> sumo
[ind2]     cmd: sumo -c "C:\R_and_D\digital-twin\sumo\od-prediction\sim.sumocfg" --route-files "C:\Users\milad\AppData\Local\Temp\tmpnf7oa9ho\routes.rou.xml" --additional-files "C:\Users\milad\AppData\Local\Temp\tmpnf7oa9ho\meandata.add.xml" --no-step-log true --no-warnings true
[ind2]     rc=0  elapsed=25.05s
[ind2] edges.xml: exists=True  size=127819
[ind2] edges.xml head:
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-09T01:31:37.743894+03:30 by Eclipse SUMO sumo 1.26.0
<sumoConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>

[ind2] sim edges=360  common=359  score=0.036895
[ind2] ── DONE  total=28.01s ──────────
  → ind2 score=0.036895  (6/6 done)
  Gen 29 done in 28.4s  scores=['0.0558', '0.0292', '0.0369', '0.0674', '0.0328', '0.0273']
  All-time best: 0.024652

============================================================
  TIMING SUMMARY
============================================================
   Gen   Time(s)      Gen Best   All-time Best
  ----  --------  ------------  --------------
     0      25.4      0.039404        0.039404
     1      22.0      0.031477        0.031477
     2      20.0      0.033258        0.031477
     3      21.6      0.037118        0.031477
     4      21.7      0.033157        0.031477
     5      23.0      0.033112        0.031477
     6      26.4      0.030510        0.030510
     7      25.6      0.040453        0.030510
     8      21.6      0.031465        0.030510
     9      26.7      0.032352        0.030510
    10      19.3      0.036637        0.030510
    11      19.9      0.033490        0.030510
    12      21.7      0.032461        0.030510
    13      22.6      0.027630        0.027630
    14      20.8      0.030349        0.027630
    15      21.7      0.026950        0.026950
    16      25.8      0.033781        0.026950
    17      29.2      0.025325        0.025325
    18      30.1      0.029231        0.025325
    19      29.4      0.026701        0.025325
    20      33.5      0.026190        0.025325
    21      31.2      0.027923        0.025325
    22      26.1      0.026962        0.025325
    23      27.2      0.024652        0.024652
    24      33.4      0.029309        0.024652
    25      27.9      0.039722        0.024652
    26      26.2      0.026071        0.024652
    27      25.1      0.031673        0.024652
    28      31.2      0.030547        0.024652
    29      28.4      0.027329        0.024652
============================================================
  Total wall time : 764.5s  (12.7 min)
  Generations run : 30
  Avg gen time    : 25.5s
  Best score      : 0.024652
============================================================

DONE — best score: 0.024652
Saved final_od.xml
(.env) 
milad@Milad MINGW64 /c/R_and_D/digital-twin/sumo/od-prediction
$ `

In [9]:
import xml.etree.ElementTree as ET
import numpy as np
import os

TAZ_FILE    = "grids.taz.xml"
abs_taz    = os.path.abspath(TAZ_FILE)

tree  = ET.parse(abs_taz)
zones = [t.attrib["id"] for t in tree.getroot().findall("taz")]
n     = len(zones)
print(f"  zones: {n}  first 3: {zones[:3]}")

def load_od_from_xml(xml_file="final_od.xml", zones=None):
    """
    Load OD matrix from SUMO od.xml / final_od.xml file
    
    Parameters:
        xml_file: path to the OD XML file
        zones: list of zone ids in correct order (if None, will extract from file)
    
    Returns:
        od_matrix (numpy array), zones (list)
    """
    tree = ET.parse(xml_file)
    root = tree.getroot()
    
    # Extract all tazRelations
    relations = []
    for interval in root.findall("interval"):
        for rel in interval.findall("tazRelation"):
            from_zone = rel.get("from")
            to_zone = rel.get("to")
            count = int(rel.get("count", 0))
            relations.append((from_zone, to_zone, count))
    
    # Get all unique zones
    all_zones = set()
    for f, t, _ in relations:
        all_zones.add(f)
        all_zones.add(t)
    
    zone_list = sorted(all_zones) if zones is None else zones
    n = len(zone_list)
    zone_index = {zone: idx for idx, zone in enumerate(zone_list)}
    
    # Create matrix
    od_matrix = np.zeros((n, n), dtype=int)
    
    for from_zone, to_zone, count in relations:
        if from_zone in zone_index and to_zone in zone_index:
            i = zone_index[from_zone]
            j = zone_index[to_zone]
            od_matrix[i, j] = count
    
    print(f"Loaded OD matrix from {xml_file}")
    print(f"Shape: {od_matrix.shape} | Total trips: {od_matrix.sum()}")
    
    return od_matrix, zone_list


# ========================= USAGE =========================

# Load with existing zones (recommended)
od_matrix, loaded_zones = load_od_from_xml("final_od.xml", zones=zones)

print("Matrix shape:", od_matrix.shape)
print("Sample (top-left 5x5):")
print(od_matrix)

# Or load without passing zones (auto-detects)
# od_matrix, loaded_zones = load_od_from_xml("final_od.xml")

  zones: 12  first 3: ['0_3', '1_1', '1_2']
Loaded OD matrix from final_od.xml
Shape: (12, 12) | Total trips: 6978
Matrix shape: (12, 12)
Sample (top-left 5x5):
[[  0  67  87  63  53  21  41  82  47  64  94  54]
 [ 33   0   1  72  39  83  62  15  30  82  66  24]
 [ 15  94   0  12  28 100  39  37  51  65  30  69]
 [ 38  34  14   0  59  73  34  59  79  90  50  56]
 [ 28  98   5  93   0  38   7  93  56  50  66  48]
 [  3   4  20  42  10   0  64  78  90   0  97  54]
 [ 13  21  55  47  97  54   0  94  61  68  15  72]
 [ 96  21  83  46  82  82  87   0  87  76  40  24]
 [ 31  64  98  39  98  33  40  65   0  23  91  26]
 [ 48  28  34  12  57  90  62   6  64   0  36  85]
 [ 79  79  11  64  47   0  66  63   4  63   0  45]
 [ 66  54  71  95  74   0  80  46  21  64  85   0]]
